// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASONJaYyPxY4Ry1ffDgg9BAONHtCc1Qdo',
    appId: '1:766311177211:web:3529b4884e247e7d24895e',
    messagingSenderId: '766311177211',
    projectId: 'iverson-4d06a',
    authDomain: 'iverson-4d06a.firebaseapp.com',
    storageBucket: 'iverson-4d06a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWhePnRkrHgOh3Q86gSR8OJ9lVKNlgf6E',
    appId: '1:766311177211:android:7a8995560c6b124024895e',
    messagingSenderId: '766311177211',
    projectId: 'iverson-4d06a',
    storageBucket: 'iverson-4d06a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2DRHST-0ccQRuwiOmKrzDCgltdtEzvOI',
    appId: '1:766311177211:ios:84a89a149b6b66f524895e',
    messagingSenderId: '766311177211',
    projectId: 'iverson-4d06a',
    storageBucket: 'iverson-4d06a.appspot.com',
    androidClientId: '766311177211-09muvfck1n8bq4elttngjv3qhvvpbfqu.apps.googleusercontent.com',
    iosClientId: '766311177211-3u0ksui9u4s5cj6pmn9tod1861feib7q.apps.googleusercontent.com',
    iosBundleId: 'com.morpheus.iverson',
  );
}
